import '../style/output.css' //tailwindcss

export const metadata = {
  title: '청약정보 모아보기',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">

      <body className='px-8 py-4'>
        {children}</body>
    </html>
  )
}
