import '../style/output.css' //tailwindcss

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
        <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1>
        {children}</body>
    </html>
  )
}
